# Generated by Django 4.0.3 on 2022-04-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=100, max_length=255),
        )
    ]
