name: App Workflows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  django_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
