# This is an sample workflow for learning  working-directory option
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
name: CI
 
jobs:
  phpunit:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run Django CI
      working-directory: backend
