name: CI

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Directory
        working-directory: backend
        run: cp .env.example .env
